# Generated by Django 5.1.3 on 2024-11-22 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtcarsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='clientes_interessados',
        ),
        migrations.AddField(
            model_name='carro',
            name='clientes_reservados',
            field=models.ManyToManyField(blank=True, related_name='carros_reservados', to=settings.AUTH_USER_MODEL),
        ),
    ]
