# Generated by Django 5.1.3 on 2024-11-22 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtcarsApp', '0002_remove_carro_clientes_interessados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='clientes_interessados',
            field=models.ManyToManyField(blank=True, related_name='carros_interessados', to=settings.AUTH_USER_MODEL),
        ),
    ]
